import {type NextPage} from "next";
import Head from "next/head";
import Link from "next/link";

import {Button} from "~/components/ui/button";

import {signIn, signOut, useSession} from "next-auth/react";

const Home: NextPage = () => {
  const {data: session} = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-8 px-4 py-8">
          <h1 className="text-3xl font-extrabold tracking-normal text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">EasyInvoice</span>
          </h1>
          <p className="font-bold">Effortlessly Create, Send, and Manage Invoices</p>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">Log in and start managing your invoices. </div>
              <Button variant="default" size={"sm"} onClick={session ? () => void signOut() : () => void signIn()}>
                {session ? "Sign out" : "Sign in"}
              </Button>
              <Button size={"sm"} variant={"link"} asChild>
                <Link href="employee/dashboard/invoices">Invoices</Link>
              </Button>
            </div>
          </div>

          <p className="px-2 text-lg font-semibold">
            Welcome to EasyInvoice, the hassle-free solution for effortless invoicing. Say goodbye to complex
            spreadsheets and time-consuming paperwork.
          </p>

          {/* <p>
            With EasyInvoice, creating, sending, and managing invoices is a breeze. Enjoy the convenience of automated
            invoicing, personalized branding, and real-time tracking. Whether you're a freelancer or a small business
            owner, EasyInvoice streamlines your financial management. Start optimizing your invoicing process today with
            EasyInvoice.
          </p> */}
        </div>
      </main>
    </>
  );
};

export default Home;
