import {type NextPage} from "next";
import Head from "next/head";
import Link from "next/link";

import {Button} from "~/components/ui/button";

import {signIn, signOut, useSession} from "next-auth/react";
import {Avatar, AvatarFallback, AvatarImage} from "~/components/ui/avatar";
import {getNameInitials} from "~/lib/utils";
import {env} from "~/env.mjs";

const Home: NextPage = () => {
  const {data: session} = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-8 px-4 py-8">
          <h1 className="text-3xl font-extrabold tracking-normal text-[hsl(280,100%,70%)] sm:text-[5rem]">
            EasyInvoice
          </h1>
          <p className="text-center text-sm font-bold text-white sm:text-lg">
            Effortlessly Create, Send, and Manage Invoices
          </p>

          <div className="grid grid-cols-1 gap-4 md:gap-8">
            <div className="flex max-w-xs flex-col items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">Start managing your invoices.</div>

              {session && (
                <Avatar
                  className="h-8 w-8 border border-gray-700 dark:border dark:border-gray-500 sm:h-10 sm:w-10"
                  asChild
                >
                  <Link href="admin/dashboard">
                    <AvatarImage
                      src={session?.user.image ?? undefined}
                      alt={`Profile picture of ${session?.user.name ?? "user logged"}`}
                    />
                    <AvatarFallback>{getNameInitials(session?.user.name ?? "AA")}</AvatarFallback>
                  </Link>
                </Avatar>
              )}

              <Button
                variant="default"
                size={"sm"}
                onClick={
                  session
                    ? () => void signOut()
                    : () =>
                        void signIn("google", {
                          redirect: true,
                          callbackUrl: `${env.NEXT_PUBLIC_BASE_URL}/admin/dashboard`,
                        })
                }
              >
                {session ? "Sign out" : "Sign in"}
              </Button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
